#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --job-name=vit-mvf-onecycle
#SBATCH --gpus=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=24:00:00
#SBATCH --mem=120000MB
#SBATCH --output=job_logs/thesis_results/ViT_masks/MVFusion_3D_small_6views_hotfixed.out

cd $HOME/DeepViewAgg

module purge
source activate pytorch3d

export HYDRA_FULL_ERROR=1

export 'PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512'


./scripts/train_superconvergence.sh