#!/bin/bash

#SBATCH --partition=gpu_titanrtx_shared
#SBATCH --gpus=1
#SBATCH --job-name=sparseconv3d
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=6
#SBATCH --time=60:00:00
#SBATCH --mem=180000M
#SBATCH --output=job_logs/dva/train_sparseconv3d.out

cd $HOME/DeepViewAgg

module purge

module load 2021
module load CUDA/11.3.1

#export C_INCLUDE_PATH="/home/fsun/DeepViewAgg/sparsehash:$CPLUS_INCLUDE_PATH"
export HYDRA_FULL_ERROR=1

./scripts/train_scannet.sh