#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --job-name=mvf_l
#SBATCH --gpus=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=30:00:00
#SBATCH --mem=120000MB
#SBATCH --output=job_logs/superconvergence/MVFusion_3D_large_6views_2d_supervision/ViT_masks_run_1.out

cd $HOME/DeepViewAgg

module purge
source activate pytorch3d

export HYDRA_FULL_ERROR=1

./scripts/train_superconvergence.sh