#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --job-name=mvf_bs3
#SBATCH --gpus=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=50:00:00
#SBATCH --mem=120000MB
#SBATCH --output=job_logs/superconvergence/view_selection_experiment/ViT_masks_MVFusion_medium_6views_bs3_lr0.01.out

cd $HOME/DeepViewAgg

module purge
source activate pytorch3d

export HYDRA_FULL_ERROR=1

./scripts/train_scannet_mvfusion.sh
